# Generated by Django 4.2.21 on 2025-07-12 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_date']},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='auteur',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='categorie',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='contenu',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='date_publication',
            new_name='published_date',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='titre',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='nom',
            new_name='name',
        ),
    ]
